name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20.x]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Enable Corepack 📦
        run: corepack enable

      - name: Setup node env 🔧
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies 👨🏻‍💻
        run: yarn install --immutable

      - name: Run linter 👀
        run: yarn lint

      - name: Build with Next.js 🏗
        run: yarn build
